globalThis.PSJModules = globalThis.PSJModules || {};
const expose = (name, value) => {
  globalThis[name] = value;
  globalThis.PSJModules = globalThis.PSJModules || {};
  return value;
};
function niceScale(){const r=ui.canvas.getBoundingClientRect(),target=70/app.camera.z;const bases=[.1,.2,.5,1,2,5,10,20,50,100,200,500,1000,2000,5000,10000];return bases.reduce((a,b)=>Math.abs(b-target)<Math.abs(a-target)?b:a,bases[0])}
function resize(){const dpr=devicePixelRatio||1,r=ui.canvas.getBoundingClientRect();ui.canvas.width=Math.max(1,Math.floor(r.width*dpr));ui.canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function draw(){const r=ui.canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);drawGrid(r);const av=app.avatarView;if(app.follow&&av.correctedLocal){app.camera.x+=(av.correctedLocal.x-app.camera.x)*.12;app.camera.y+=(av.correctedLocal.y-app.camera.y)*.12}if(app.layers.trail)drawTrail();if(app.layers.controls)drawControlPoints();drawRecords();drawActive();drawAvatar();drawScale();updateInfo()}
function drawGrid(r){ctx.fillStyle='#dfe8e8';ctx.fillRect(0,0,r.width,r.height);const step=40;ctx.strokeStyle='rgba(20,80,95,.12)';ctx.lineWidth=1;for(let x=((r.width/2-(app.camera.x*app.camera.z))%step+step)%step;x<r.width;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,r.height);ctx.stroke()}for(let y=((r.height/2+(app.camera.y*app.camera.z))%step+step)%step;y<r.height;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(r.width,y);ctx.stroke()}}
function dot(l,col,rad=4){const p=localToScreen(l.x,l.y);ctx.beginPath();ctx.arc(p.x,p.y,rad,0,Math.PI*2);ctx.fillStyle=col;ctx.fill()}
function drawTrail(){app.tempGnss.slice(-80).forEach((g,i)=>{const l=g.displayLocal||g.correctedLocal||g.rawLocal||g.local;if(!l)return;dot(l,g.quality==='outlier'?'rgba(181,74,60,.35)':`rgba(28,102,116,${.08+i/120})`,2.2)})}
function drawControlPoints(){app.controlPoints.forEach(cp=>{const l=cp.personalLocal;const p=localToScreen(l.x,l.y);const rr=Math.max(8,Math.min(80,(cp.influenceRadius||20)*app.camera.z));ctx.beginPath();ctx.arc(p.x,p.y,rr,0,Math.PI*2);ctx.strokeStyle=`rgba(216,174,91,${.25+.45*(cp.confidence||.2)})`;ctx.lineWidth=2;ctx.stroke();dot(l,'#d8ae5b',5);ctx.fillStyle='#2b2115';ctx.font='11px system-ui';ctx.fillText(`Ïƒ ${(cp.sigmaM||0).toFixed(1)}m`,p.x+7,p.y-7)})}
function drawLine(verts,col='#936b35',dash=false){if(!verts?.length)return;ctx.beginPath();verts.forEach((v,i)=>{const l=v.correctedLocal||v.local||v;const p=localToScreen(l.x,l.y);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.strokeStyle=col;ctx.lineWidth=3;if(dash)ctx.setLineDash([8,6]);ctx.stroke();ctx.setLineDash([])}
function drawPoly(verts){if(!verts?.length)return;ctx.beginPath();verts.forEach((v,i)=>{const l=v.correctedLocal||v.local||v,p=localToScreen(l.x,l.y);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});if(verts.length>2)ctx.closePath();ctx.fillStyle='rgba(120,185,201,.18)';ctx.fill();ctx.strokeStyle='#1c6674';ctx.lineWidth=2;ctx.stroke()}
function drawIcon(l,icon='âœ¦',size=1){const p=localToScreen(l.x,l.y);ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor='rgba(0,0,0,.32)';ctx.shadowBlur=8;ctx.font=`${Math.max(16,20*size)}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icon,0,0);ctx.restore()}
function drawRecords(){for(const r of visibleRecords()){if(r.type==='point'&&app.layers.objects)drawIcon(r.correctedLocal||r.local,r.icon||'âœ¦',r.iconScale||1);if(r.type==='route'&&app.layers.routes)drawLine(r.vertices,'#936b35');if(r.type==='area'&&app.layers.areas)drawPoly(r.vertices);if(r.type==='circle'&&app.layers.areas)drawLine(r.vertices,'#4bc7d9')}}
function drawActive(){if(app.active?.type==='route')drawLine(app.active.vertices,'#b54a3c',true);if(app.active?.type==='area')drawPoly(app.active.vertices);if(app.selectBox){ctx.save();const r=ui.canvas.getBoundingClientRect();const x1=app.selectBox.x1-r.left,y1=app.selectBox.y1-r.top,x2=app.selectBox.x2-r.left,y2=app.selectBox.y2-r.top;ctx.strokeStyle='rgba(102,217,232,.9)';ctx.fillStyle='rgba(102,217,232,.12)';ctx.setLineDash([6,4]);ctx.strokeRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.fillRect(Math.min(x1,x2),Math.min(y1,y2),Math.abs(x2-x1),Math.abs(y2-y1));ctx.restore()}}
function drawAvatar(){const av=app.avatarView,l=av.correctedLocal;if(!l)return;const p=localToScreen(l.x,l.y),acc=Math.max(4,Math.min(160,(av.accuracy||8)*app.camera.z));ctx.beginPath();ctx.arc(p.x,p.y,acc,0,Math.PI*2);ctx.strokeStyle='rgba(181,74,60,.32)';ctx.lineWidth=2;ctx.stroke();const sr=niceScale();ctx.beginPath();ctx.arc(p.x,p.y,sr*app.camera.z,0,Math.PI*2);ctx.strokeStyle='rgba(28,102,116,.42)';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.stroke();ctx.setLineDash([]);const a=(av.heading||0)*Math.PI/180;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(a);ctx.fillStyle='#172c32';ctx.strokeStyle='#fffaf0';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(9,10);ctx.lineTo(0,5);ctx.lineTo(-9,10);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.sin(a)*38,p.y-Math.cos(a)*38);ctx.strokeStyle='rgba(255,207,101,.85)';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='rgba(120,185,201,.18)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.arc(p.x,p.y,48,-Math.PI/2+a-.35,-Math.PI/2+a+.35);ctx.closePath();ctx.fill()}
function drawScale(){const sr=niceScale();app.settings.scaleRing=sr;ui.scaleLabel.textContent=`r = ${fmtM(sr)}`}
function updateInfo(){const av=app.avatarView,w=av.correctedWgs||av.rawWgs,sel=safeDate(app.settings.selectedAt);ui.info1.textContent=`Real ${new Date().toLocaleString()} Â· Selected ${sel.toLocaleDateString()} Â· ${app.settings.viewMode.toUpperCase()} Â· W${weekNo(sel)}`;ui.info2.textContent=w?`WGS ${w.lat?.toFixed?.(6)}, ${w.lng?.toFixed?.(6)}, ground z ${(w.alt||0).toFixed(1)} Â· acc ${av.accuracy?.toFixed?.(1)||'â€”'}m Â· solver ${av.solver} Â· CP ${app.controlPoints.length} Â· origin ${app.crs.originInitialized?'set':'pending'}`:'Fallback avatar Â· no GPS yet';ui.northNeedle.style.transform='rotate(0deg)';ui.headingNeedle.style.transform=`rotate(${app.avatarView.heading||0}deg)`;const gx=Math.max(-18,Math.min(18,app.orientation.gamma||0)), by=Math.max(-18,Math.min(18,app.orientation.beta||0));ui.bubble.style.transform=`translate(${gx}px,${by}px)`;if(ui.levelerBubble)ui.levelerBubble.style.transform=`translate(${Math.max(-20,Math.min(20,gx))}px,${Math.max(-20,Math.min(20,by))}px)`}

function renderAll(dbDirty=true){if(dbDirty)buildViews();draw()}


export { niceScale, resize, draw, drawGrid, dot, drawTrail, drawControlPoints, drawLine, drawPoly, drawIcon, drawRecords, drawActive, drawAvatar, drawScale, updateInfo, renderAll };
Object.assign(globalThis.PSJModules.rendering = {}, { niceScale, resize, draw, drawGrid, dot, drawTrail, drawControlPoints, drawLine, drawPoly, drawIcon, drawRecords, drawActive, drawAvatar, drawScale, updateInfo, renderAll });
for (const [name, value] of Object.entries(globalThis.PSJModules.rendering)) expose(name, value);

