globalThis.PSJModules = globalThis.PSJModules || {};
const expose = (name, value) => {
  globalThis[name] = value;
  globalThis.PSJModules = globalThis.PSJModules || {};
  return value;
};
function solvePosition(raw){const local=raw.rawLocal;let sx=0,sy=0,sz=0,sw=0,used=[];for(const cp of app.controlPoints){const d=Math.max(1,distanceLocal(local,cp.personalLocal||cp.correctedLocal||cp.local));const sigma=Math.max(0.5,cp.sigmaM||cp.sigma||5);const radius=cp.influenceRadius||Math.max(20,80/(cp.confidence||.3));if(d>radius)continue;const w=(cp.confidence||.5)/(sigma*sigma*d*d);const dx=cp.weightedDelta?.dx||cp.delta?.dx||0,dy=cp.weightedDelta?.dy||cp.delta?.dy||0,dz=cp.weightedDelta?.dz||cp.delta?.dz||0;sx+=dx*w;sy+=dy*w;sz+=dz*w;sw+=w;used.push({id:cp.id,w,d,sigma})}
 const corrected=sw?{x:local.x-sx/sw,y:local.y-sy/sw,z:local.z-sz/sw}:{...local};const confidence=sw?Math.min(1,.35+Math.log10(1+sw)*.25):Math.max(.05,1/(1+(raw.accuracy||50)/8));return{rawLocal:{...local},estimatedLocal:{...corrected},correctedLocal:{...corrected},correctedWgs:localToWgs(corrected.x,corrected.y,corrected.z),confidence,usedControls:used,solver:sw?'weighted-control-field':'raw-fallback'}}
function rejectOutlier(raw){const last=app.tempGnss.at(-1);if(!last)return false;const dt=(new Date(raw.capturedAt)-new Date(last.capturedAt))/1000;if(dt<=0)return true;const d=distanceLocal(raw.rawLocal,last.rawLocal||last.local);const speed=d/dt;return (raw.accuracy&&last.accuracy&&raw.accuracy>Math.max(80,last.accuracy*4))||speed>80||(app.stationary.locked&&d>30)}
async function ingestGps(c){const rawWgs={lat:c.latitude,lng:c.longitude,alt:normalizedPhoneAlt(c.altitude),phoneAlt:normalizedPhoneAlt(c.altitude),groundAlt:normalizedPhoneAlt(c.altitude)-PHONE_HEIGHT_OFFSET_M,accuracy:c.accuracy??null,altitudeAccuracy:c.altitudeAccuracy??null,speed:c.speed??null,heading:c.heading??null};const rawLocal=wgsToLocal(rawWgs.lat,rawWgs.lng,rawWgs.alt);const raw={id:id('GPS'),rawWgs,rawLocal,wgs:rawWgs,local:rawLocal,accuracy:rawWgs.accuracy,altitudeAccuracy:rawWgs.altitudeAccuracy,capturedAt:new Date().toISOString(),quality:'raw',usedInSolver:true};if(rejectOutlier(raw)){raw.quality='outlier';raw.usedInSolver=false;app.tempGnss.push(raw);await put('tempGnss',raw);return}
 const sol=solvePosition(raw);const prev=app.avatarView.correctedLocal;const d=prev?distanceLocal(prev,sol.correctedLocal):999;const isStill=(rawWgs.speed||0)<.35&&d<Math.max(2,(rawWgs.accuracy||20)*.18);if(isStill&&prev){sol.correctedLocal={...prev};sol.estimatedLocal={...prev};sol.correctedWgs=localToWgs(prev.x,prev.y,prev.z)}
 app.avatarView={...app.avatarView,id:'avatar',rawWgs,rawLocal,estimatedLocal:sol.estimatedLocal,correctedLocal:sol.correctedLocal,correctedWgs:sol.correctedWgs,accuracy:rawWgs.accuracy,altitudeAccuracy:rawWgs.altitudeAccuracy,confidence:sol.confidence,solver:sol.solver,usedControls:sol.usedControls,updatedAt:raw.capturedAt,heading:computeHeading(rawWgs,sol.correctedLocal)};raw.solver=sol;raw.displayLocal=sol.correctedLocal;app.tempGnss.push(raw);while(app.tempGnss.length>1200)app.tempGnss.shift();await put('tempGnss',raw);await put('avatarView',app.avatarView);learnStationary(raw,sol);sampleActiveFromAvatar();buildViews();renderAll(false)}
function computeHeading(rawWgs,loc){let h=app.lastGoodHeading||0;if(typeof rawWgs.heading==='number'&&rawWgs.speed>.8)h=rawWgs.heading;else if(app.orientation.alpha!==null)h=(360-app.orientation.alpha+360)%360;else{const last=app.tempGnss.filter(g=>g.displayLocal).at(-1);if(last&&distanceLocal(last.displayLocal,loc)>1){const a=last.displayLocal,b=loc;h=(Math.atan2(b.x-a.x,b.y-a.y)*180/Math.PI+360)%360}}
 if(Math.abs(((h-app.lastGoodHeading+540)%360)-180)>150&&(!rawWgs.speed||rawWgs.speed<.4))h=app.lastGoodHeading;app.lastGoodHeading=angleLerp(app.lastGoodHeading||h,h,.25);return app.lastGoodHeading}
function learnStationary(raw,sol){const s=app.stationary;s.samples.push({raw,sol});if(s.samples.length>36)s.samples.shift();const recent=s.samples.slice(-12);if(recent.length<8)return;const center=recent[0].sol.correctedLocal;const maxD=Math.max(...recent.map(x=>distanceLocal(center,x.sol.correctedLocal)));const avgAcc=recent.reduce((a,x)=>a+(x.raw.accuracy||50),0)/recent.length;if(maxD<2.5){if(!s.locked)s.locked={local:{...center},startedAt:new Date().toISOString()};for(const x of recent.slice(-1)){const dx=x.raw.rawLocal.x-s.locked.local.x,dy=x.raw.rawLocal.y-s.locked.local.y,dz=x.raw.rawLocal.z-s.locked.local.z;app.correctionLog.push({id:id('RES'),type:'stationary-residual',t:x.raw.capturedAt,rawLocal:x.raw.rawLocal,lockedLocal:s.locked.local,dx,dy,dz,dt:(new Date(x.raw.capturedAt)-new Date(s.locked.startedAt))/1000,accuracy:x.raw.accuracy,weight:1/Math.max(1,(x.raw.accuracy||20)**2)});put('correctionLog',app.correctionLog.at(-1))}if(recent.length>=12&&avgAcc<35){const cp=makeControlFromSamples(recent,s.locked.local,avgAcc);if(!nearExistingCp(cp)) {app.controlPoints.push(cp);put('controlPoints',cp)}}}else{s.locked=null}}
function nearExistingCp(cp){return app.controlPoints.some(c=>distanceLocal(c.personalLocal,cp.personalLocal)<3)}
function makeControlFromSamples(samples,locked,avgAcc){let sw=0,sx=0,sy=0,sz=0;const residuals=samples.map(x=>{const dx=x.raw.rawLocal.x-locked.x,dy=x.raw.rawLocal.y-locked.y,dz=x.raw.rawLocal.z-locked.z,w=1/Math.max(1,(x.raw.accuracy||20)**2);sw+=w;sx+=dx*w;sy+=dy*w;sz+=dz*w;return{t:x.raw.capturedAt,dx,dy,dz,accuracy:x.raw.accuracy,w}});const md={dx:sx/sw,dy:sy/sw,dz:sz/sw};const sig=Math.sqrt(residuals.reduce((a,r)=>a+r.w*((r.dx-md.dx)**2+(r.dy-md.dy)**2+(r.dz-md.dz)**2),0)/sw);return{id:id('CP'),type:'control-point',createdAt:new Date().toISOString(),personalLocal:{...locked},personalWgs:localToWgs(locked.x,locked.y,locked.z),weightedDelta:md,sigmaM:sig,avgAccuracy:avgAcc,samples:samples.length,confidence:Math.max(.2,Math.min(1,1/(1+sig/5)*1/(1+avgAcc/40))),influenceRadius:Math.max(15,80/(1+sig)),residuals}}
async function getGps(){return new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>res(p.coords),rej,{enableHighAccuracy:true,timeout:12000,maximumAge:0}):rej(new Error('GPS unavailable')))}
async function refreshGps(){try{const c=await getGps();await ingestGps(c)}catch(e){ui.info2.textContent='GPS not available yet Â· fallback avatar active'}}
function startGpsLoop(){refreshGps();setInterval(refreshGps,Math.max(1,app.settings.gnssInterval)*1000)}


export { solvePosition, rejectOutlier, ingestGps, computeHeading, learnStationary, nearExistingCp, makeControlFromSamples, getGps, refreshGps, startGpsLoop };
Object.assign(globalThis.PSJModules.solver = {}, { solvePosition, rejectOutlier, ingestGps, computeHeading, learnStationary, nearExistingCp, makeControlFromSamples, getGps, refreshGps, startGpsLoop });
for (const [name, value] of Object.entries(globalThis.PSJModules.solver)) expose(name, value);

